# Generated by Django 3.2 on 2022-11-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite',
            field=models.ManyToManyField(related_name='favs', to='webapp.Photo', verbose_name='Избранные'),
        ),
    ]
